'use server';

/**
 * @fileOverview This file defines a Genkit flow for analyzing click patterns to detect bots.
 *
 * The flow takes click data as input and uses an LLM to determine the likelihood of bot activity.
 * It exports the `analyzeClickPatterns` function, the `AnalyzeClickPatternsInput` type, and the `AnalyzeClickPatternsOutput` type.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeClickPatternsInputSchema = z.object({
  clickTimestamps: z
    .array(z.number())
    .describe('An array of timestamps representing user clicks.'),
  ipAddress: z.string().describe('The IP address of the user.'),
  userAgent: z.string().describe('The user agent string of the user.'),
});

export type AnalyzeClickPatternsInput = z.infer<typeof AnalyzeClickPatternsInputSchema>;

const AnalyzeClickPatternsOutputSchema = z.object({
  isBotLikely: z
    .boolean()
    .describe(
      'A boolean indicating whether the click pattern is likely generated by a bot.'
    ),
  confidenceScore: z
    .number()
    .describe(
      'A score between 0 and 1 indicating the confidence level of the bot detection.'
    ),
  reasoning: z
    .string()
    .describe(
      'A detailed explanation of why the click pattern is classified as bot-like or not.'
    ),
});

export type AnalyzeClickPatternsOutput = z.infer<typeof AnalyzeClickPatternsOutputSchema>;

export async function analyzeClickPatterns(
  input: AnalyzeClickPatternsInput
): Promise<AnalyzeClickPatternsOutput> {
  return analyzeClickPatternsFlow(input);
}

const analyzeClickPatternsPrompt = ai.definePrompt({
  name: 'analyzeClickPatternsPrompt',
  input: {schema: AnalyzeClickPatternsInputSchema},
  output: {schema: AnalyzeClickPatternsOutputSchema},
  prompt: `You are an expert in detecting bots based on user click patterns.

You are provided with the following information:

- Click Timestamps: {{{clickTimestamps}}}
- IP Address: {{{ipAddress}}}
- User Agent: {{{userAgent}}}

Analyze the click pattern and determine if it is likely generated by a bot.
Consider factors such as the frequency of clicks, the consistency of intervals between clicks, and any anomalies that suggest automated behavior.

Provide a confidence score between 0 and 1 (where 1 is very confident) to indicate the likelihood of bot activity.

Also, explain your reasoning for the classification.
`,
});

const analyzeClickPatternsFlow = ai.defineFlow(
  {
    name: 'analyzeClickPatternsFlow',
    inputSchema: AnalyzeClickPatternsInputSchema,
    outputSchema: AnalyzeClickPatternsOutputSchema,
  },
  async input => {
    const {output} = await analyzeClickPatternsPrompt(input);
    return output!;
  }
);
